addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("io.github.davidmweber"     % "flyway-sbt"          % "7.4.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.29")
addSbtPlugin("com.codecommit"            % "sbt-github-actions"  % "0.13.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
